### ISSUE TITLE
Data points are accumulated when the tab is not focused

### ISSUE THREAD

**Issue by MasterBabol** [emilmork/react-rt-chart#13]
It seems C3 still accumulates points when the tab is not focused: https://github.com/c3js/c3/issues/1097, and this affects react-rt-chart as well since it is using C3 0.4.10.

**Comment by MasterBabol** [comment]
Well, unfortunately, c3@0.6.8 does not appear to resolve this problem.

![image](https://user-images.githubusercontent.com/17945273/46654371-aae5c600-cbe3-11e8-852e-760118acaef2.png)

**Comment by emilmork** [comment]
@MasterBabol I see. 

I think this must be fixed in c3 or be a part of your own implementation. Not in react-rt-chart.


As suggested on the c3 forum, you could try to check if the page/tab is in foucs with [page visibility api](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) and dont add new values to react-rt-chart while the page is out of focus.

When the page is in focus you could reset the chart with the latest values.

**Comment by MasterBabol** [comment]
I think the logic would be a boilerplate; but I understand.
In fact, I'm already using the workaround for this.
