### ISSUE TITLE
TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by ThomasBourgeois** [emilmork/react-rt-chart#9]
I think there is a problem with the new version of react that does not contain any more React.PropTypes .  (cf : https://reactjs.org/docs/typechecking-with-proptypes.html and https://stackoverflow.com/questions/44573199/cannot-read-property-string-of-undefined-react-proptypes-layoutproptypes-j )

I have a bug when running my  app including react-rt-chart, it says : 
" TypeError: Cannot read property 'string' of undefined
./node_modules/react-rt-chart/dist/index.js
*/node_modules/react-rt-chart/dist/index.js:183
  180 | },
  181 | 
  182 | propTypes: {
> 183 |   dateFormat: _react2.default.PropTypes.string,
  184 |   chart: _react2.default.PropTypes.object,
  185 |   fields: _react2.default.PropTypes.array.isRequired,
  186 |   maxValues: _react2.default.PropTypes.number
View compiled
__webpack_require__
*/webpack/bootstrap 1c03f8e0442af5a58e73:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
*/webpack/bootstrap 1c03f8e0442af5a58e73:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
"

etc.

**Comment by ThomasBourgeois** [comment]
Note : downgrading react to "16.0.0-alpha.12" solves it temporarily.

**Comment by gio00** [comment]
`React.PropTypes` and `React.createClass` have been moved to their own packages. The old way it's deprecated. Look here https://reactjs.org/blog/2017/04/07/react-v15.5.0.html

**Comment by loneScripter** [comment]
To fix this I first:
`npm i prop-types`

Then I found the index and found the part that you're looking at here:
`183 | dateFormat: _react2.default.PropTypes.string,
184 | chart: _react2.default.PropTypes.object,
185 | fields: _react2.default.PropTypes.array.isRequired,
186 | maxValues: _react2.default.PropTypes.number`

You should go to the top of this file and import prop-types:
`import PropTypes from 'prop-types';`

Then go back down to lines 183/186 and change them like so:
`  propTypes: {
    dateFormat: PropTypes.date,
    chart: PropTypes.object,
    fields: array.isRequired,
    maxValues: PropTypes.number
  }`

Following this I was presented with a few more issues I'm currently trying to work over but I'm certain that this problem is solved and now a thing of the past.
